package com.selenium.orange_project.AllPages;

import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;

import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.testng.Assert;

import com.selenium.orange_project.BasePages.BaseActions;
import com.selenium.orange_project.Config.Readers;

public class AddEmployee extends BaseActions{

	public AddEmployee() {
		PageFactory.initElements(getDriver(),this);
	}
	
	@FindBy(xpath = "//nav[@aria-label='Topbar Menu']//child::li[3]")
	WebElement AddEmployeeButton;
	
	@FindBy(xpath = "//nav[@aria-label='Topbar Menu']//child::li[2]")
	WebElement EmployeeListButton;
	
	@FindBy(xpath = "//label[normalize-space()='Employee Id']/following::input[1]")
	WebElement EmployeeId;
	
	@FindBy(xpath = "//input[@name='firstName']")
	WebElement firstName;
	
	@FindBy(xpath = "//input[@name='lastName']")
	WebElement lastName;
	
	@FindBy(xpath = "//button[normalize-space()='Save']")
	WebElement submitButton;
	
	@FindBy(xpath = "//span[normalize-space()='Employee Id already exists']")
	WebElement alreadyExist;
	
	@FindBy(xpath = "(//div[@class='oxd-autocomplete-wrapper']//input)[1]")
	WebElement nameFilter;  
	
	@FindBy(xpath = "(//div[@class='oxd-select-wrapper']//i)[1]")
	WebElement DropDownEmployeeStatus;
	
	@FindBy(xpath = "(//div[@class='oxd-select-text-input'])[1]")
	WebElement StatusValue;
	
	@FindBy(xpath = "//button[@type='submit']")
	WebElement SearchButton;
	
	@FindBy(xpath = "//p[@class='oxd-userdropdown-name']")
	WebElement AdminName;
	
	@FindBy(xpath = "//div[@class='oxd-table-card']")
	List<WebElement> EmployeeCount;
	
	@FindBy(xpath = "(//div[@class='oxd-table-card'])[1]")
	WebElement FirstElement;
	
	@FindBy(xpath = "//ul[@class='oxd-pagination__ul']/li")
	List<WebElement> CountPage;
	
	@FindBy(xpath = "//ul[@class='oxd-pagination__ul']//i[contains(@class,'chevron-right')]")
	WebElement NextRecordpage;
	
	@FindBy(xpath = "//div[contains(@class,'orangehrm-horizontal-padding orangehrm-vertical-padding')]/span")
	WebElement TotalRecordFetch;
	
	public void ValidateTheEmployee() throws IOException {
		try {
			waitForVisbility(AddEmployeeButton,10);
			AddEmployeeButton.click();
			waitForVisbility(EmployeeId,10);
			String employeeid = EmployeeId.getAttribute("value");
			System.out.println("Autogenerated id: "+employeeid);
			Map<String,String> ExcelData = ExcelReader();
			firstName.sendKeys(ExcelData.get("FirstName"));
			lastName.sendKeys(ExcelData.get("LastName"));
			submitButton.click();
			if(Displayed(alreadyExist))
			{
				int RandomNumber = RandomId();
				EmployeeId.sendKeys(String.valueOf(RandomNumber));
				submitButton.click();
			}
			else {
				waitForVisbility(AddEmployeeButton,10);
				AddEmployeeButton.click();
				waitForVisbility(EmployeeId,10);
				EmployeeId.click();
				EmployeeId.clear();
				EmployeeId.sendKeys(employeeid);
				submitButton.click();
				firstName.sendKeys(ExcelData.get("FirstName"));
				lastName.sendKeys(ExcelData.get("LastName"));
				submitButton.click();
				Assert.assertTrue(
					Displayed(alreadyExist),
					"Verification Failed : Employee ID does not exist :"+ employeeid
						
						);
				System.out.println("Verification Passed : Employee Id exist"+employeeid);
			}
		}
		 catch (Exception e) {
			e.printStackTrace();
		}

	}
	
	
	public void Search_With_Filter() throws IOException {
		
		Boolean Pass = false;
		
		waitForVisbility(EmployeeListButton,10);
		EmployeeListButton.click();
		waitForVisbility(nameFilter, 10);
		Map<String,String> ExcelData = ExcelReader();
		String adminName = AdminName.getText(); 
		String adminName1 = adminName.trim().replaceAll("\\s+"," ");
		nameFilter.sendKeys(adminName.trim().split("\\s+")[0]);
		for(int i = 0; i<10; i++) 
		{
			nameFilter.sendKeys(Keys.ARROW_DOWN);
			String ActualName = nameFilter.getAttribute("value");
			
				if(ActualName.contains(adminName1.split("\\s+")[0]))
				{
					nameFilter.sendKeys(Keys.ENTER);
					System.out.println("Verifcaition Passed : Entered the name"+ActualName);
					Pass = true;
					break;
				}
						
		}	
		
		Assert.assertTrue(Pass,"Expected name is not found in DropDown");
		String ExpectedStatus =  ExcelData.get("StatusFilter").trim().replace("\\s+"," ");
		DropDownEmployeeStatus.click();
		StatusValue.sendKeys(Keys.ARROW_DOWN);
		while(!StatusValue.getText().equalsIgnoreCase(ExpectedStatus))
		{
			
			StatusValue.sendKeys(Keys.ARROW_DOWN);
			System.out.println(StatusValue.getText());
		}
			Assert.assertEquals(StatusValue.getText(),
					ExpectedStatus,
					"Expected Status was not Selected"
					);
			StatusValue.sendKeys(Keys.ENTER);
			System.out.println("Verification Passed : Selectd Expected Status : "+ExpectedStatus);
			SearchButton.click();
			
	}
	
		public void EmployeeeCount() {
			
			int count = 1;
			int totalRecord = 0;
			waitForVisbility(EmployeeListButton,10);
			EmployeeListButton.click();
			waitForVisbility(FirstElement, 10);
			int TotalRecordDisplay = Integer.parseInt(TotalRecordFetch.getText().replaceAll("[^0-9]",""));
			while(true) {
				try {
					
					waitForVisbility(FirstElement, 10);
					System.out.println("Number of Employee Count in "+count+" Page: "+EmployeeCount.size());
					totalRecord += EmployeeCount.size();
					NextRecordpage.click();
					count++;
				} catch (Exception e) {
					System.out.println("Next page button is over");
					break;
					
				}
	
			}
			
			System.out.println("Total Number of records : "+totalRecord);
			Assert.assertEquals(TotalRecordDisplay,totalRecord
					,"Total records mismatch with table count"
					);
			System.out.println("Total Records Validation Passed Total record : "+totalRecord+" Displayed Count : "+TotalRecordDisplay);
		}

}
